# Generated by Django 3.2.7 on 2021-10-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredient_meals',
            name='once_per_product_sale',
        ),
        migrations.AddConstraint(
            model_name='ingredient_meals',
            constraint=models.UniqueConstraint(fields=('meal', 'ingredient'), name='once_per_meal_ingredient'),
        ),
    ]
