# Generated by Django 3.2.7 on 2021-10-05 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_meal_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient_meals',
            name='unit',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.unit'),
            preserve_default=False,
        ),
    ]
