# Generated by Django 3.2.7 on 2021-10-05 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211005_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient_meals',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.unit'),
        ),
    ]
