# Generated by Django 3.2.7 on 2021-10-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211006_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='ingredients',
            field=models.ManyToManyField(blank=True, through='api.Ingredient_Meals', to='api.Ingredient'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='meals',
            field=models.ManyToManyField(blank=True, through='api.Ingredient_Meals', to='api.Meal'),
        ),
    ]
