# Generated by Django 3.2.7 on 2021-10-06 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20211006_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='units',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.unit'),
            preserve_default=False,
        ),
    ]
