# Generated by Django 3.2.7 on 2021-10-06 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_meal_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='units',
        ),
    ]
