# Generated by Django 3.2.7 on 2021-10-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20211006_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='counter',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='meal',
            name='day',
            field=models.SmallIntegerField(default=1),
        ),
    ]
