# Generated by Django 3.2.7 on 2021-10-09 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20211009_0338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='ingredient_meals',
            name='quantity',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=999),
        ),
    ]
