# Generated by Django 3.2.7 on 2021-10-09 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20211009_0354'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quantity',
        ),
    ]
