# Generated by Django 3.2.7 on 2021-10-09 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_ingredient_meals_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='units',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='ingredients',
        ),
    ]
