# Generated by Django 3.2.7 on 2021-10-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20211009_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='units',
            field=models.ManyToManyField(blank=True, through='api.Ingredient_Meals', to='api.Unit'),
        ),
    ]
