# Generated by Django 3.2.7 on 2021-10-09 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20211009_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient_meals',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ingredient_Meals', to='api.ingredient'),
        ),
    ]
