# Generated by Django 3.2.7 on 2021-10-09 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_ingredient_meals_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient_meals',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='api.ingredient'),
        ),
    ]
