# Generated by Django 3.2.7 on 2021-10-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_ingredient_meals_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='ingredients',
            field=models.ManyToManyField(through='api.Ingredient_Meals', to='api.Ingredient'),
        ),
    ]
