# Generated by Django 3.2.7 on 2021-10-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20211009_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='ingredient_type',
            field=models.CharField(default=1, max_length=100, verbose_name='ingredient type'),
            preserve_default=False,
        ),
    ]
