# Generated by Django 3.2.7 on 2021-10-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_ingredient_ingredient_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='ingredient_type',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='meal',
            field=models.ManyToManyField(through='api.Ingredient_Meals', to='api.Meal'),
        ),
    ]
