# Generated by Django 3.2.7 on 2021-10-10 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20211010_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient_meals',
            old_name='unit',
            new_name='units',
        ),
    ]
