# Generated by Django 3.2.7 on 2021-10-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_rename_unit_ingredient_meals_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=999),
        ),
    ]
