# Generated by Django 3.2.7 on 2021-10-11 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_remove_ingredient_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient_meals',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
