# Generated by Django 3.2.7 on 2021-10-11 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_rename_ingredient_ingredient_meals_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient_meals',
            old_name='ingredients',
            new_name='ingredient',
        ),
    ]
