# Generated by Django 3.2.7 on 2021-10-11 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_rename_ingredients_ingredient_meals_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient_meals',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='api.meal'),
        ),
    ]
