# Generated by Django 3.2.7 on 2021-10-11 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_ingredient_meals_meal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='ingredients',
            new_name='ingredient',
        ),
        migrations.AlterField(
            model_name='ingredient_meals',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='api.ingredient'),
        ),
        migrations.AlterField(
            model_name='ingredient_meals',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.meal'),
        ),
    ]
