# Generated by Django 3.2.7 on 2021-10-11 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20211011_1148'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredient_Meals',
            new_name='IngredientMeals',
        ),
    ]
