# Generated by Django 3.2.7 on 2021-10-11 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_rename_ingredient_meals_ingredientmeals'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='ngredientmeals',
            field=models.ForeignKey(default=56, on_delete=django.db.models.deletion.CASCADE, related_name='ngredientmeals', to='api.ingredientmeals'),
            preserve_default=False,
        ),
    ]
