# Generated by Django 3.2.7 on 2021-10-11 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_meal_ngredientmeals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientmeals',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='igredientmeals', to='api.meal'),
        ),
    ]
