# Generated by Django 3.2.7 on 2021-10-12 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_ingredientmeals_meal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='test', max_length=32, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='ingredientmeals',
            old_name='units',
            new_name='unit',
        ),
    ]
