# Generated by Django 3.2.7 on 2021-10-12 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20211012_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientmeals',
            name='spice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='spices', to='api.spices'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spices',
            name='name',
            field=models.CharField(default='', max_length=32, null=True),
        ),
    ]
