# Generated by Django 3.2.7 on 2021-10-12 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20211012_1219'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spices',
            new_name='Spice',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='ngredientmeals',
        ),
    ]
