# Generated by Django 3.2.7 on 2021-10-12 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20211012_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientmeals',
            name='spice',
        ),
        migrations.AddField(
            model_name='meal',
            name='spice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='spices', to='api.spice'),
            preserve_default=False,
        ),
    ]
