# Generated by Django 3.2.7 on 2021-10-13 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_alter_meal_spice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='spice',
            options={'ordering': ['name']},
        ),
    ]
